### ISSUE TITLE
flamenco_manager setup wizard insists on blender install

### ISSUE THREAD

**Issue by jrwarwick** [MOZGIII/flamenco-docker#1]
After getting the images and stages built, starting up the manager results in a first-time setup wizard which eventually prompts for the path to blender. 
![image](https://github.com/MOZGIII/flamenco-docker/assets/1444084/a6eb2844-c241-4b6f-8bd7-fa5472682d5b)

My solution was to rearrange the stages so that manager is derivative of worker, and specifying /usr/local/bin/blender :
https://github.com/MOZGIII/flamenco-docker/compare/master...jrwarwick:flamenco-docker:master

If there is an alternative to that, perhaps a short README.md with a note about it would avoid getting stuck on this. 

Thanks for sharing this, very useful project.

**Comment by MOZGIII** [comment]
I made various changes to the image such that the whole setup assistance is now skipped.
Please close if this has solved your issue.

**Comment by jrwarwick** [comment]
Thank you, that worked perfectly. And the docker compose file makes this even more quick and convenient. Thanks again!
